# Generated by Django 5.1.7 on 2026-01-10 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='media/profile_images')),
                ('fullname', models.CharField(max_length=50)),
                ('phone', models.CharField(default=23480000000000, max_length=20)),
                ('bio', models.TextField(default='Am using ChatFlow...')),
                ('address', models.CharField(default='Address not updated', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
