# Generated by Django 5.1.7 on 2026-01-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHATAPP', '0003_alter_profile_address_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Am using ChatFlow...'),
        ),
    ]
