# Generated by Django 5.1.7 on 2026-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHATAPP', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='/default_image/5856.jpg', upload_to='media/profile_images'),
        ),
    ]
