# Generated by Django 5.1.7 on 2026-01-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHATAPP', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='group_avater/')),
                ('about', models.TextField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('QR_code', models.FileField(blank=True, null=True, upload_to='QR_codes/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(to='CHATAPP.profile')),
            ],
        ),
    ]
