# Generated by Django 5.1.7 on 2026-01-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHATAPP', '0008_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='dicription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
