# Generated by Django 5.1.7 on 2026-01-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHATAPP', '0010_alter_chatroom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='dicription',
            new_name='discription',
        ),
    ]
